<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="scannell" uri="https://www.envirosaas.com/tags"%>


<!DOCTYPE html>
<html>
<head>
	<meta name="printable" content="true">
	<title></title>
	<script type="text/javascript" >
var load_image, validateExtension;

load_image = function(id, ext, input) {  
  if (validateExtension(ext) === false) {
    bootbox.alert('Upload only JPEG, PNG, GIFF, GIF or JPG format ');
    document.getElementById('content').focus();
    document.getElementById('save').disabled = 1;
    return;
  }
  // document.getElementById('save').disabled = 0;
  if (input.files && input.files[0]) {
	  var imageSize = parseInt((input.files[0].size/1024));
		 if(imageSize > 3000){
			 document.getElementById('content').focus();
	          document.getElementById('save').disabled = 1;
	          jQuery('#theImg').removeAttr('src');
			 alert('<fmt:message key="imageTooBig" />');
			 return;
		 }
	  var reader = new FileReader();
      reader.onload = function (e) {
      	jQuery('#imageDiv').text('');
      	jQuery("#imageDiv").show();
      	jQuery('#imageDiv').prepend('<img id="theImg" src="e.target.result" alt="" border=3   />');
      	jQuery("#theImg").attr("src",e.target.result);
      	// should create this parallel proccess otherwise it will not work for chrome
	    /*  setTimeout(function (){
	      	imageheight = document.getElementById('theImg').naturalHeight;
	        imagewidth = document.getElementById('theImg').naturalWidth;
	        if (imageheight < 100 || imagewidth < 100) {
	          document.getElementById('content').focus();
	          //document.getElementById('save').disabled = 1;
	          jQuery('#theImg').removeAttr('src');
	          //bootbox.alert('Image selected is too small. Please select a larger Image');
	        }
	      }, 500);*/
      	//jQuery('#theImg').Jcrop();
      	//cropImage();
      }

      reader.readAsDataURL(input.files[0]);
    
  }
};

validateExtension = function(v) {
  var allowedExtensions, ct, sample;
  allowedExtensions = new Array('jpg', 'JPG', 'jpeg', 'JPEG', 'giff', 'GIFF', 'gif', 'GIF', 'png', 'PNG');
  ct = 0;
  while (ct < allowedExtensions.length) {
    sample = v.lastIndexOf(allowedExtensions[ct]);
    if (sample !== -1) {
      return true;
    }
    ct++;
  }
  return false;
};

// ---
// generated by coffee-script 1.9.2
	
function savePictogram(){
	var jsonData = new FormData();
	
	//jsonData.append("pictogramme", JSON.stringify(updateJson()));
	jsonData.append('optionId', '<c:out value="${option.id}" />');
	jsonData.append("pictogram", jQuery("#theImg").attr("src"));
	var request = new XMLHttpRequest();
	request.open('POST', '<c:url value="/system/savePictogram.htm" />');
	request.send(jsonData);
	request.onreadystatechange = function() {
		
		if (request.readyState == XMLHttpRequest.DONE) {
			 if(request.status === 200){  //check if "OK" (200)
				if(request.responseText.indexOf("result:OK") > -1){
						location.href = 'questionView.htm?id=<c:out value="${option.question.id}" />';
				} else {
					alert('<fmt:message key="inspectionTemplateSaveError" />');
				}
		     }
			 jQuery("#saveButton").attr("disabled", false);	
			 jQuery("#saveButton2").attr("disabled", false);
		}
    }
	
}
</script>
</head>
<body>
<div class="header">
<h2><fmt:message key="questionOptionView" /></h2>
</div>
<div class="content">
<div class="table-responsive">
<div class="panel">
<table class='table table-responsive table-bordered'>
	<tbody>
		<tr>
			<td ><fmt:message key="name" />:</td>
			<td><c:out value="${option.name}" /></td>
		</tr>
		<%-- <tr>
			<td ><fmt:message key="furtherInfo" />:</td>
			<td><c:out value="${option.furtherInfo}" /></td>
		</tr> --%>
		<tr>
			<td ><fmt:message key="order" />:</td>
			<td><c:out value="${option.optionOrder}" /></td>
		</tr>
		<tr>
			<td ><fmt:message key="active" />:</td>
			<td><fmt:message key="${option.activeIgnoringSite}" /></td>
		</tr>
	    <c:if test="${option.activeIgnoringSite}">
	      <tr>
	        <td ><fmt:message key="questionOption.activeInSites" />:</td>
	        <td>
	          <ul>
	            <c:forEach items="${activeInSites}" var="site">
	              <li><c:out value="${site.name}" /></li>
	            </c:forEach>
	          </ul>
	        </td>
	      </tr>
	    </c:if>
	  		<%-- <tr>
			<td ><fmt:message key="visible" />:</td>
			<td><fmt:message key="${option.visible}" /></td>
		</tr> --%>
		<tr>
			<td ><fmt:message key="question" />:</td>
			<td><a href="<c:url value="questionView.htm"><c:param name="id" value="${option.question.id}" /></c:url>"><c:out value="${option.question.name}" /></a></td>
		</tr>
		<c:if test="${option.question.pictogramActive}">
		<tr>
			<td ><fmt:message key="pictograme" />:</td>
			<td>
				<scannell:form enctype="multipart/form-data">
					<input id="content" type="file" name="picture" class="wide" accept="image/*" onChange="load_image(this.id,this.value,this)"/>
					<div class="image" id='imageDiv' style="width: 100; height: 100; ${option.id > 0 && option.pictogram != '' && option.pictogram != null ? '' : 'display: none;'}">
					 	<c:if test="${option.id > 0 && option.pictogram != '' && option.pictogram != null}"><img class="printImageSize matrixImageSize" src="${option.pictogram}" alt="" border="3" /></c:if> 
					 </div>
					 <input id="save" type="button" onclick="savePictogram()" class="g-btn g-btn--primary" style="margin-top:15px" value="<fmt:message key="submit" />">
				</scannell:form>
			</td>
		</tr>
		</c:if>
		<tr>
			<td ><fmt:message key="dependsOn" />:</td>
			<c:choose>
				<c:when test="${optionMulti == null}">
					<td><a href="<c:url value="questionOptionView.htm"><c:param name="id" value="${option.dependsOn.id}" /></c:url>"><c:out value="${option.dependsOn.name}" /></a></td>
				</c:when>
				<c:otherwise>
					<c:forEach items="${optionMulti}" var="opt">
						<tr><td></td><td><a href="<c:url value="questionOptionView.htm"><c:param name="id" value="${opt.id}" /></c:url>"><c:out value="${opt.name}" /></a></td><tr>
	  				</c:forEach>
				</c:otherwise>
			</c:choose>
		</tr>
		</tbody>
	<tfoot>
		<tr>
			<td colspan="2">
				<scannell:url urls="${urls}" /> 
			</td>
		</tr>
	</tfoot>
</table>
</div>
</div>
</div>
</body>
</html>
