package com.ideagen.qhse.orm.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * RiskBusinessArea generated by hbm2java
 */
@Entity
@Table(name = "risk_business_area")
@NamedQueries({
    @NamedQuery(name = "riskBusinessArea.listActive", query = "from RiskBusinessArea a where a.active = true order by a.name, a.id"),
    @NamedQuery(name = "riskBusinessArea.listAll", query = "from RiskBusinessArea a order by a.name, a.id"),
    @NamedQuery(name = "riskBusinessArea.listByName", query = "from RiskBusinessArea a where a.name = :name")
})
public class RiskBusinessArea extends AbstractNamedEntity {

	private Boolean active;

	public RiskBusinessArea() {
	}
	
	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
